import type { NextPage } from 'next'
import Head from 'next/head'
import { programOne, programTwo } from '../data/programs'

const Home: NextPage = () => {
  return (
    <div className="bg-black h-screen">
      <Head>
        <title>Fitness Programs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-24">
        <section className="max-w-4xl mx-auto">
          <h1 className="font-bold text-transparent text-4xl bg-clip-text bg-gradient-to-r from-violet-500 to-fuchsia-500">
            Fitness Programs
          </h1>
          <div className="space-y-4 mt-4">
            <div className="h-2 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500"></div>
            <div className="text-gray-50">
              <h2 className="text-gray-100 text-xl font-semibold">
                {programOne.name}
              </h2>
              {programOne.workouts.map(({ day, name, exercises }) => (
                <div className="ml-4">
                  <div className="text-gray-400 text-lg font-semibold">
                    Day: {day} Workout: {name}
                  </div>
                  <div>
                    {exercises.map(({ name, sets }) => (
                      <div className=" border-t-2 max-w-xs mt-2">
                        <div className="flex justify-between mt-2">
                          <div className="ml-4">{name}</div>
                          <div className="flex flex-col">
                            {sets &&
                              sets.map((set, i) => (
                                <div className="">
                                  {i} Set {set} Reps
                                </div>
                              ))}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
            <div className="h-2 rounded-lg bg-gradient-to-r from-sky-500 to-indigo-500"></div>
            <div className="h-2 rounded-lg bg-gradient-to-r from-violet-500 to-fuchsia-500"></div>
            <div className="h-2 rounded-lg bg-gradient-to-r from-purple-500 to-pink-500"></div>
          </div>
        </section>
      </main>

      <footer className=""></footer>
    </div>
  )
}

export default Home
