import type { NextPage } from 'next'
import Head from 'next/head'
import { programs } from '../data/programs'
import Program from '../components/Program'
import { ProgramCard } from '../components/ProgramCard'

const Home: NextPage = () => {
  return (
    <div className="bg-[#080808]">
      <Head>
        <title>Open Fit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-24">
        <section className="max-w-4xl mx-auto">
          <h1 className="font-muli font-semibold text-[116px] text-transparent leading-[132px] tracking-[-5.336px] bg-clip-text bg-gradient-to-r from-violet-500 to-fuchsia-500">
            <div className="text-white"> Workout</div>
            <div>Programs</div>
          </h1>

          <div className="grid grid-cols-3 gap-8 mt-8">
            {Object.values(programs).map((program, i) => (
              <ProgramCard key={i} program={program} />
            ))}

            <div className="aspect-square rounded-lg bg-gradient-to-r from-violet-500 to-fuchsia-500" />
            <div className="aspect-square rounded-lg bg-gradient-to-r from-purple-500 to-pink-500" />
            <div className="aspect-square rounded-lg bg-gradient-to-r from-teal-500 to-sky-500" />
            <div className="aspect-square rounded-lg bg-gradient-to-r from-pink-500 to-red-500" />
          </div>

          {/* <div className="space-y-4 mt-4">
            <div className="rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500" />
            <div className="rounded-lg bg-gradient-to-r from-sky-500 to-indigo-500" />
            <div className="rounded-lg bg-gradient-to-r from-violet-500 to-fuchsia-500" />
            <div className="rounded-lg bg-gradient-to-r from-purple-500 to-pink-500" />
          </div> */}
        </section>
      </div>
    </div>
  )
}

export default Home
